version: '3.1'

services:
  collector_service:
    image: joyzoursky/python-chromedriver:3.8-selenium
    ports:
      - "5000:5000"
    volumes:
      - "./collector:/collector"
      - "./requirements.txt:/requirements.txt"
    command: bash -c "
        pip install -U pip;
        pip install -U setuptools;
        pip install -r requirements.txt;
        python collector/app.py"
