version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7
    steps:
    - checkout
    - run:
        name: Setup testing environment
        command: |
          pip install -r requirements.txt
          echo $HOME
    - run:
        name: Run Tests
        command: |
          $HOME/.local/bin/coverage run -m pytest
          $HOME/.local/bin/coverage report
          $HOME/.local/bin/coverage html  # open htmlcov/index.html in a browser
    - store_artifacts:
        path: htmlcov
workflows:
  version: 2
  workflow:
    jobs:
    - build
